### PR TITLE
Add drag-to-refresh handling

### LINKED ISSUE #28: Add drag-to-refresh
The user needs to be able to refresh their files to see new changes. Normally this is being done by "pulling" down the screen revieling a loading animation (not necessary). Then the files should be refetched. This functionality should be implemented in the tabs/files.tsx component I guess.

### PR DESCRIPTION
**Pull request by theopfr**
Closes #28 

I added the functionality for refreshing the file data on the phone to be in sync with nextcloud. I also made it so that deleting a file in, eg the courses tab will also remove the file in the activity tab without refreshing. One thing I noticed is that when deleting a file you get a warning popup saying "Possibly unhandled promise rejection" but I just couldn't find the cause. it doesnt break anything but it still bugs me... Anyways, this led me to also slightly rewrite the request functions for fetching downloading and deleting files becasue it makes error handling simpler. I hope this doesnt create a conflict with any of you. Cheers

### CODE REVIEW

**Comment by cma5** [comment]
while testing, I got some problems:
Android: 
When deleting

**Comment by cma5** [comment]
IPhone:
Sadly it get's worse :/

https://github.com/lern-fair-file-sharing/app/assets/68401216/8f948e48-58e9-4786-827c-ef193ff2871d

I have isolated the issue:

When deleting it without downloading, it works fine but gives me the unhandled promise rejection. The file is gone.

When I try to download and then to delete it, it gives me a 412 on delete and when I refresh, the file appears again like you see in the video.

grafik

**Comment by cma5** [comment]
When trying to download on android:

But the files are downloaded anyway.

**Comment by cma5** [comment]
IPhone:

https://github.com/lern-fair-file-sharing/app/assets/68401216/8f948e48-58e9-4786-827c-ef193ff2871d

I have isolated the issue:

When deleting it without downloading, it works fine but gives me the unhandled promise rejection. The file is gone.

When I try to download and then to delete it, it gives me a 412 on delete and when I refresh, the file appears again like you see in the video.

grafik

**Comment by theopfr** [comment]
> while testing, I got some problems: Android: When deleting 

Yes I mentioned this in my PR description. Not sure what to do about that tbh.

**Comment by theopfr** [comment]
> When trying to download on android:  But the files are downloaded anyway.

Thanks for catching, should work now on Android at least!

**Comment by theopfr** [comment]
> IPhone:
> 
>  RPReplay_Final1718962341.MP4 
> I have isolated the issue:
> 
> When deleting it without downloading, it works fine but gives me the unhandled promise rejection. The file is gone.
> 
> When I try to download and then to delete it, it gives me a 412 on delete and when I refresh, the file appears again like you see in the video.
> 
> grafik

Ugh Apple again, but good that you checked on iOS too. I'll continue solving this issue using my iPad and come back to you!

**Comment by theopfr** [comment]
> IPhone:
> 
>  RPReplay_Final1718962341.MP4 
> I have isolated the issue:
> 
> When deleting it without downloading, it works fine but gives me the unhandled promise rejection. The file is gone.
> 
> When I try to download and then to delete it, it gives me a 412 on delete and when I refresh, the file appears again like you see in the video.
> 
> grafik

Damn on my iPad it works like a charm for me. Both the download and deletion.. @cma5

**Review by cma5 — APPROVED** [review]
Well, you did it. Congrats!

**Comment by theopfr** [comment]
Let me document the problem we ran it and "how we solved it":
On iOS you could download and delete files normally. Except when you downloaded a file you we not able to delete it afterwards, only files you didn't download. We got a 412 error when downloading those files and the error message was ``An If-None-Match header was specified, but the ETag matched (or * was specified).``. Which we don't really understand and it also seems to make no sense at all. It seems that in the background iOS sometimes adds this header but how does it decide to only add this to the delete-request of files which were previously downloaded. Anyways I fixed it by adding
```js
requestHeaders.append("If-none-match", "areyoukiddingmeapple");
```
Note that the value is randomly chosen.

**Pull request merged**
